config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :users, only: [:show] do
    resources :festivals, only: [:show, :index]
  end
  resources :festivals
  resources :festivals, only: [:show] do
    resources :artists, only: [:index, :new, :create]
    resources :comments
  end

  resources :artists
  root 'welcome#home'
  post 'index' => 'festivals#index'
  get 'index' => 'festivals#index'
  post 'attend' => 'users#attend'
  delete 'unattend' => 'users#unattend'
  get 'festivals/:id/going' => 'festivals#going', as: 'going'
  get 'festivals/:id/interested' => 'festivals#interested', as: 'interested'
  get 'festivals/:id/approve' => 'festivals#approve', as: 'approve'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :festivals, through: :artist_festivals
	has_many :artist_festivals
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
		if params[:festival_id]
			@festival = Festival.find(params[:festival_id])
			@artists = @festival.artists
		end
	end

	def new
		@festival = Festival.find(params[:festival_id])
		@artist = Artist.new()
	end

	def create
		@festival = Festival.find(params["artist"]["festival_id"])
		@artist = Artist.find_or_create_by(name: params["artist"]["name"])
		ArtistFestival.create(artist_id: @artist.id, festival_id: @festival.id, description: params["artist"]["description"])
		redirect_to festival_artists_path(@festival)
	end

	def artist_params
		params.require(:artist).permit(:name, :description)
	end
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/views/artists/index.html.erb
<div class="user-field">
<h2>Here are some of the greatest names <br> of the <%= @festival.name %> line up:</h2>
<% @artists.each do |artist|%>
Name: <%= artist.name %><br>
Description: <%= ArtistFestival.find_by(artist_id: artist.id, festival_id: @festival.id).description %><br>
<% end %>
<%= link_to "Add new artist", new_festival_artist_path %>
</div>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
<%= f.label :name %></br>
<%= f.text_field :name %></br>
<%= f.label :description %></br>
<%= f.text_field :description %></br>
<%= f.hidden_field :festival_id, value: @festival.id %>
<%= f.submit %> 
<% end %>