config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :users, only: [:show] do
    resources :festivals, only: [:show, :index]
  end
  resources :festivals
  resources :festivals, only: [:show] do
    resources :artists, only: [:index, :new, :create]
    resources :comments
  end

  resources :artists
  root 'welcome#home'
  post 'index' => 'festivals#index'
  get 'index' => 'festivals#index'
  post 'attend' => 'users#attend'
  delete 'unattend' => 'users#unattend'
  get 'festivals/:id/going' => 'festivals#going', as: 'going'
  get 'festivals/:id/interested' => 'festivals#interested', as: 'interested'
  get 'festivals/:id/approve' => 'festivals#approve', as: 'approve'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_festival
  has_many :comments
  has_many :festivals, through: :user_festival
  has_many :created_festivals, :foreign_key=>"creator_id", class_name: Festival
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  validates :name, presence: true
  def set_default_role
    self.role ||= :user
  end
  
 def self.from_omniauth(auth)
    where(provider: auth[:provider], uid: auth.uid).first_or_create do |user|
      user.email = auth[:info][:email]
      user.name = auth[:info][:name]
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
 	  sign_in_and_redirect @user 
  end

  def google_oauth2
  	@user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show 
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
		user.update(user_params)
		redirect_to user_path(user)
	end

	def festivals_index
		@user = current_user
    	@festivals = Festival.where(creator_id: current_user.id)
    	render template: 'festivals/index'
	end

	def festival
	end

	def attend
		user = User.find(params[:user_id])
		festival = Festival.find(params[:festival_id])
		user.user_festival.create(festival_id: params[:festival_id], status:"going")
		festival_data = {username: user.name, userpath: user_path(user)}
		render json: festival_data
	end

	def unattend
		user = User.find(params[:user_id])
		festival = Festival.find(params[:festival_id])
		user.user_festival.find_by(festival_id: festival.id).delete
		festival_data = {username: user.name, userpath: user_path(user)}
		render json: festival_data
	end

	private

	def user_params
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f|%>
<%= f.label :name %></br>
<%= f.text_field :name %></br>
<%= f.label :email %></br>
<%= f.text_field :email %></br>
<%= f.submit %>
<%end%>

app/views/users/show.html.erb
<div class="user-field">
<% if @user.name %>
	Name: <%= @user.name%></br>
<% end %>
Email: <%= @user.email %></br>
<div class="btn">
<% if @user == current_user %>
	<%= link_to "Edit Profile", edit_user_path(current_user) %><br>
<% end %>
</div><br>
Upcoming Events: 
<% if UserFestival.going.where(user_id: @user.id).count == 0 %>
	nothing here yet
<% else %>
	<% UserFestival.going.where(user_id: @user.id).to_a.each do |userfestival| %>
		<% festival = Festival.find(userfestival.festival_id) %>
		<%= link_to festival.name, festival_path(festival) %>
	<% end %>
<% end %>
<br>

Saved Events:
<% if UserFestival.interested.where(user_id: @user.id).count == 0 %>
	nothing here yet
<% else %>
	<% UserFestival.interested.where(user_id: @user.id).to_a.each do |userfestival| %>
		<% festival = Festival.find(userfestival.festival_id) %>
		<%= link_to festival.name, festival_path(festival) %>
	<% end %>
<% end %><br>
<% if @user == current_user %>
	<% if Festival.where(creator_id: current_user.id).count != 0 %>
	<div class="btn">
	<% if @user == current_user %>
		<%= link_to "My Festivals", user_festivals_path(current_user) %>
	<% end %>
	</div>
<% end %>
<% end %>
</div>