config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :users, only: [:show] do
    resources :festivals, only: [:show, :index]
  end
  resources :festivals
  resources :festivals, only: [:show] do
    resources :artists, only: [:index, :new, :create]
    resources :comments
  end

  resources :artists
  root 'welcome#home'
  post 'index' => 'festivals#index'
  get 'index' => 'festivals#index'
  post 'attend' => 'users#attend'
  delete 'unattend' => 'users#unattend'
  get 'festivals/:id/going' => 'festivals#going', as: 'going'
  get 'festivals/:id/interested' => 'festivals#interested', as: 'interested'
  get 'festivals/:id/approve' => 'festivals#approve', as: 'approve'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		if current_user
			@user = current_user 
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<div id="home">
<% if !current_user %>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>
<h1>FESTIVALOCATOR</h1>
	<div class="button"><%= link_to "sign in", new_user_session_path %></div>
	<div class="button"><%= link_to "sign up", new_user_registration_path %></div><br>
	<div class="button-long"><%= link_to "login with Facebook!", user_facebook_omniauth_authorize_path %></div></br>
	<div class="button-long"><%= link_to "login with Google!", user_google_oauth2_omniauth_authorize_path %></div></br>
<% end %>
<% if current_user %>
<div id="explore-button-frame">
	<div id="explore-button">
		<div id="explore">
			<%= link_to "EXPLORE", festivals_path %> <br>
		</div>
	</div>
</div>
<% end %>
</div>