config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :users, only: [:show] do
    resources :festivals, only: [:show, :index]
  end
  resources :festivals
  resources :festivals, only: [:show] do
    resources :artists, only: [:index, :new, :create]
    resources :comments
  end

  resources :artists
  root 'welcome#home'
  post 'index' => 'festivals#index'
  get 'index' => 'festivals#index'
  post 'attend' => 'users#attend'
  delete 'unattend' => 'users#unattend'
  get 'festivals/:id/going' => 'festivals#going', as: 'going'
  get 'festivals/:id/interested' => 'festivals#interested', as: 'interested'
  get 'festivals/:id/approve' => 'festivals#approve', as: 'approve'

end

app/models/festival.rb
class Festival < ActiveRecord::Base
	belongs_to :category
	belongs_to :world_part
	has_many :user_festival
	has_many :comments
	has_many :users, through: :user_festival
	has_many :artist_festivals
	has_many :artists, through: :artist_festivals
	belongs_to :creator, class_name: User, :foreign_key=>"creator_id"
	validates :name, :category, :location, :world_part, :line_up, :website, presence: true
	accepts_nested_attributes_for :artists

	def artists_attributes=(artists)
		artists.each do |id, hash|
			artist = Artist.find_or_create_by(name: hash[:name])
		end
	end
end

# What is our attribute writer trying to accomplish
 # This existst on the new festival form
 # Create a new festival
 # add a row with the associations in the artist_festival table
 # find or create the artist by name

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
	def index
		@festivals = Festival.all
		if params[:user_id]
			@user_festival_path = true
			@festivals = Festival.where(creator_id: params[:user_id])
		elsif params[:world_part] && !params[:world_part].empty?
			@festivals = Festival.all.where(world_part_id: WorldPart.find_by(name: params[:world_part]))
		else
			@festivals = Festival.all
		end

		if params[:category] && !params[:world_part].empty?
			@festivals = @festivals.where(category_id: Category.find_by(name: params[:category]))
		end
	end

	def new
		@festival = Festival.new
		@festival.artists.build
		@festival.artists.build
		@festival.artists.build
	end

	def create
		@festival = Festival.create(festival_params)
		if @festival.save
			params[:festival][:artists_attributes].each do |id, artist|
				if !artist[:name].empty? && !artist[:description].empty?
					ArtistFestival.create(festival_id: @festival.id, artist_id: Artist.find_by(name: artist[:name]).id, description: artist[:description])
				end
			end
        	redirect_to festival_path(@festival)
      	else
        	render 'new'
     	end
	end

	def show
		@festival = Festival.find(params[:id])
		@comments = @festival.comments
		@comment = Comment.new
		respond_to do |f|
			f.json {render json: @festival, layout: false}
      		f.html {render :show}
    	end
	end

	def edit
		@festival = Festival.find(params[:id])
		if @festival.artists.empty?
			@festival.artists.build
			@festival.artists.build
			@festival.artists.build
		end
		render :layout => false
	end

	def update
		@festival = Festival.find(params[:id])
		@festival.update(festival_params)
		# render 'festivals/show'
		params[:festival][:artists_attributes].each do |id, artist|
				if !artist[:name].empty? && !artist[:description].empty?
					ArtistFestival.create(festival_id: @festival.id, artist_id: Artist.find_by(name: artist[:name]).id, description: artist[:description])
			end
		end
		render json: @festival
	end

	def destroy
		@festival = Festival.find(params[:id])
		@festival.destroy
		redirect_to festivals_path
	end

	def going
		@festival = Festival.find(params[:id])
		userfestival = UserFestival.find_or_create_by(user_id: current_user.id, festival_id: @festival.id) 
		userfestival.status = "going"
		userfestival.save
		flash[:notice] = "You are now attending #{@festival.name}!"
		redirect_to festival_path(@festival)
	end

	def interested
		@festival = Festival.find(params[:id])
		userfestival = UserFestival.find_or_create_by(user_id: current_user.id, festival_id: @festival.id)
		userfestival.status = "interested"
		userfestival.save
		flash[:notice] = "You have successfully saved #{@festival.name}!"
		redirect_to festival_path(@festival)
	end

	def approve	
		@festival = Festival.find(params[:id])
		@festival.approved = true
		@festival.save
		flash[:notice] = "#{@festival.name} approved!"
		redirect_to index_path
	end

	private

	def festival_params
		params.require(:festival).permit(:id, :name, :category_id, :location, :venue, :line_up, :website, :start, :end, :world_part_id, :creator_id, artists_attributes: [:name, :description])
	end
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/festivals/_form.html.erb
<% if @festival.errors.any? %>
  <div id="error-explanation">
    <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this Festival from being saved:</h2>
    <ul id="validation-messages">
    <% @festival.errors.full_messages.each do |msg| %>
      <li><%= msg %></li><br>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="festival-form">
<%= form_for @festival do |f| %>
<%= f.label :name %></br>
<%= f.text_field :name %></br>
<%= f.label :category %></br>
<%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: true)%></br>
<%= f.collection_select(:world_part_id, WorldPart.all, :id, :name, include_blank: true)%></br>
<%= f.label :location %></br>
<%= f.text_field :location %></br>
<%= f.label :venue %></br>
<%= f.text_field :venue %></br>
<%= f.label :line_up %></br>
<%= f.text_field :line_up %></br>
<%= f.label :website %></br>
<%= f.text_field :website %></br>
<%= f.label :start %>
<%= f.date_select :start %><br>
<%= f.label :end%>
<%= f.date_select :end %>
<%= f.hidden_field :creator_id, value: current_user.id %><br>
For music festivals, please add more detail about headliners:<br>
<%= f.fields_for :artists do |artist| %>
	<%= artist.label :name %>
	<%= artist.text_field :name %><br>
	<%= artist.label :description %>
	<%= artist.text_field :description %><br>
<% end %>

<%= f.submit 'Update', :class => 'update_festival'%>
<% end %>
</div>

app/views/festivals/edit.html.erb
<%= render partial: 'form' %><br>

app/views/festivals/index.html.erb
<% if flash[:notice] %>
	<div class="notice"> <%= flash[:notice]%> </div>
<% end %>

<div id="wrapper">
	<div id="add-new">
		Did we miss a cool festival? Help us by adding the event yourself!
		<%= link_to "Add New", new_festival_path%><br>
	</div>
	
	
	<div id="filter">
		<%= form_tag "/index" do %>
		<%= label_tag("Location:") %>
		<%= select_tag 'world_part', options_from_collection_for_select(WorldPart.all, :id, :name, @world_part), include_blank: true %>
		<%= label_tag("Category:") %>
		<%= select_tag 'category', options_from_collection_for_select(Category.all, :id, :name, @category), include_blank: true %>
		<%= submit_tag "Filter", :onclick => "filterFestivals(); return false;" %>
	<% end %>
	</div>

		
	

<div id="festivals-container">
	<% @festivals.each do |festival| %>
		<% if current_user.role=="admin" || @user_festival_path || festival.approved %>
					<div id="festival-item">
						<h1> <%= link_to festival.name, @user_festival_path ? user_festival_path(festival, current_user) : festival_path(festival) %></h1> <br>
						<%= festival.category.name %> Festival <br>
						<%= festival.location %> <br>
						<%= festival.start%> - <%=festival.end%><br>
						<% if festival.approved == false && current_user.role == "admin" %>
							<%= link_to "[APPROVE]", approve_path(festival) %>
						<% end %>
				</div>
		<% end %>
	<% end %>
</div>

</div>

app/views/festivals/new.html.erb
<%= render partial: 'form' %><br>

app/views/festivals/show.html.erb
<% if flash[:notice] %>
	<div class="notice"> <%= flash[:notice]%> </div>
<% end %>
<div id="festival-show">
	<div id="current-user-id" style="display: none"><%=current_user.id%></div>
	<div id="festival-id" style="display: none"><%=@festival.id%></div>
	<h2><%= @festival.name %> <br></h2>
	Category: <%= @festival.category.name %> <br>
	Location: <%= @festival.world_part.name %>, <%= @festival.location %> <br>
	Venue: <%= @festival.venue %> <br>
	Line Up: <%= @festival.line_up %> <br>
	Website: <a href="#{@festival.website}"><%= @festival.website%> </a><br>
	Start Date: <%= @festival.start %> <br>
	End Date: <%= @festival.end %> <br>
	<div class="btn">
	<% if @festival.end > Time.now.to_date %>
		<% if UserFestival.going.where(user_id: current_user.id, festival_id: @festival.id).length === 1 %>
			<button class="attend">Unattend</button>
		<% else %>
			<button class="attend">Attend</button>
		<% end %>
	</div>
	<div class="btn">
	<% else %>
		<%= link_to "I went", root_path %> <br>
	<% end %>
	</div>
	<br>

	Attendees: 
	<div id="attendees">
		<% if UserFestival.going.where(festival_id: @festival.id).to_a == [] %>
		nothing here yet 
		<% else %>
			<% UserFestival.going.where(festival_id: @festival.id).to_a.each do |userfestival| %>
				<% user = User.find(userfestival.user_id) %>
				<%= link_to user.name, user_path(user), id: user.name %>
			<% end %>
		<% end %>
	</div>

	<br>
	<div class="btn">
	<% if policy(@festival).update? %>
	     <%= link_to "Edit Festival", edit_festival_path(@festival), :class => "edit_festival" %>
	<% end %>
	<% if policy(@festival).destroy? %>
	      <%= link_to "Delete Festival",  { action: :destroy, id: @festival.id }, method: :delete %>
	<% end %>
	</div>
	<br>
	<%= link_to "Home Page", root_path %> <br>
	<% if !@festival.artists.empty? %>
		<%= link_to "More about artists", festival_artists_path(@festival) %>
	<% end %>
	
	<%= link_to "Show Comments", festival_comments_path(@festival), :class => "show_comments"%>
	<div id="comments-count"></div>
	<div id="comments"></div>
	<div id="new-comment-form"></div>
</div>



<script id="festival-template" type="text/x-handlebars-template">

	<% if flash[:notice] %>
		<div class="notice"> <%= flash[:notice]%> </div>
	<% end %>
	
		<h2>{{name}}</h2>
		<p>Category: {{category}}</p>
		<p>Location: {{world_part}}, {{location}}</p>
		<p>Venue: {{venue}}</p>
		<p>Lineup: {{line_up}}</p>
		<p>Website: <a href="{{website}}">{{website}}</a></p>
		<p>When: {{when}}</p>
		<div class="btn">
		<% if @festival.end > Time.now.to_date %>
			<%= link_to "I'm going", going_path %> 
		</div>
		<div class="btn">
			<%= link_to "I'm interested", interested_path %>
		<% else %>
			<%= link_to "I went", root_path %> <br>
		<% end %>
		</div>
		<br>

		Going: 
		<% if UserFestival.going.where(festival_id: @festival.id).to_a == [] %>
		nothing here yet 
		<% else %>
			<% UserFestival.going.where(festival_id: @festival.id).to_a.each do |userfestival| %>
				<% user = User.find(userfestival.user_id) %>
				<%= link_to user.name, user_path(user) %>
			<% end %>
		<% end %>

		Interested: 
		<% if UserFestival.interested.where(festival_id: @festival.id).to_a == [] %>
		nothing here yet 
		<% else %>
			<% UserFestival.interested.where(festival_id: @festival.id).to_a.each do |userfestival| %>
				<% user = User.find(userfestival.user_id) %>
				<%= link_to user.name, user_path(user) %>
			<% end %>
		<% end %>
		<br>
		<div class="btn">
		<% if policy(@festival).update? %>
		     <%= link_to "Edit Festival", edit_festival_path(@festival), :class => "edit_festival" %>
		<% end %>
		<% if policy(@festival).destroy? %>
		      <%= link_to "Delete Festival",  { action: :destroy, id: @festival.id }, method: :delete %>
		<% end %>
		</div>
		<br>
		<%= link_to "Home Page", root_path %> <br>
		<% if !@festival.artists.empty? %>
			<%= link_to "More about artists", festival_artists_path(@festival) %>
		<% end %>
		
		<%= link_to "Show Comments", festival_comments_path(@festival), :class => "show_comments"%>
		<div id="comments"></div>
		<div id="new-comment-form"></div>
</script>